:hp-alt-title: blogka

= 맥용 카카오톡을 까보자..

회사에서 카카오톡을 이용한 사내이벤트를 가끔 합니다. 
130여명이 되는 방에서 쿵쿵따를 하는데 뭐 상금도 걸려있고 월차도 받고 나름 참여도를 높일수있는 경품이 걸려있기에 
무시할수 없는 이벤트라 자동응답이 가능한 기능이 필요했습니다. 
누구보다 빠르게 특정 단어에 반응해 자동 참여가 되도록... 
맥을 사용하고 있기에 이번에 나온 맥용 카카오톡을 까보기로 했습니다.. 
어떤 절차로 로그인이 되는지 궁금하기도 했고 여하튼.. 시작해 봅시다. 
일단 디버거를 붙여보는게 제일 빠르겠지 하는 마음에 lldb 디버거를 실행시키고 분석해 나아갔습니다. 

RFSystemMonitor 클래스에서 시스템 idle을 체크하는거 같은데 디버거를 붙이면 
 


Process stopped !!! abort 날리네요 ㅎ



디버그 상태에선 assert를 부르는듯...  진행을 해야하니 코드를 수정해서 건너뛰게하고 리패키징후 강제진행 고고...    로그인부분을 찾아야 하는데 일단 편히 찾기위해  class-dump (http://stevenygard.com/projects/class-dump) 를 이용해 헤더파일을 추출한후  Login 이름이 들어있는 메서드를 찾아봅니다. (싸게싸게 편하게 갑시다!) class-dump 간단한 사용법은 



이러면  ~/Desktop/kakaoTalk_macc/Header 위치에 주룩주룩 헤더파일이... 뽑은후 그냥 Login으로 문자 찾기  결과 한눈에 딱들어오는 누가봐도 난 로그인에 쓰여!! 라고 말하는듯한 메서드 

- (void)loginWithEmail:(id)arg1 password:(id)arg2 uuid:(id)arg3 name:(id)arg4 force:(BOOL)arg5 passcode:(id)arg6 once:(id)arg7 autoLogin:(BOOL)arg8 success:(CDUnknownBlockType)arg9 failure:(CDUnknownBlockType)arg10;
 
"MaldiveApiClient" 클래스에 있는 요놈인가 보네요 요부분을 시작으로 분석을 시작했습니다....  30여분정도 이리저리 찍어보고 하니 대강 나오네요 아직 앱기능도 많이 없어서 크기도 크지않고  리버스 엔지니어링을 대비한 더미파일들도 없어서 금방금방 진행되었습니다.  살펴보면 초기 인증과 친구목록 , 설정등을 담당서버가  Maldive 인가 봅니다.  https를 이용하네요.    자 이제 로그인 과정의 플로우를 살펴봅시다. 처음 이메일과 패스워드를 입력하고 로그인 버튼을 누르면   카카오톡이 서버에 리퀘스트보냅니다 



음.. 뭔가를 보내내요  일단 POST 데이터를 살펴봅시다. 이메일과 패스워드, 디바이스 uuid , 맥이름, 자동로그인 유무. 이정도.. 디바이스 아이디 생성과정을 분석 해봤는데 그냥 시스템 UUID를 뽑은후  sha1과 sha256의 hash값을 붙인후 base64인코딩을 했네요. 이번엔 헤더를 살펴봅시다.

"A"필드는  맥용카카오톡/버전/언어 ,

"User-Agent" 필드엔  KT/카톡버전 Mc/맥OSX버전 언어 ( 요세미티 베타를 설치했더니 10.10으로 나오네요 괜히 올려서 버그랑 씨름을.. .. ) 자 그리고 X-VC 필드를 자세히 살펴봅시다. 이게 이 리퀘스트의 유효성을 체크하는 값이더라구요 생성방법은 

        var x_vc : NSString = "JOSH|\(user_agent)|AUSTIN|\(userEmail)|\(Properties.properties().systemUUID)"
        var hash = sha512(x_vc) as NSString;
        hash = hash.substringToIndex(0x10)
        urlRequest.setValue(hash, forHTTPHeaderField:"X-VC")
(애플이 Swift를 새로 발표해서 이번 프로젝트는 Swift로 만들고 있습니다 새로 내왔으니 사용해봐야겠지요 ㅎ )
 
JOSH|useragent값(저위에선 "KT/0.9.0 Mc/10.10 ko"이겠네요)|AUSTIN|이메일|디바이스 uuid 
이걸  sha512로 hash값을 만든후 16자리로 자르면 끝.
간단하네요 ㅎ 
아무튼 이걸 날려봅시다
돌아오는 응답은 
 

뭐 헤더엔 별게없는거같고  돌아오는 데이터 status값에 -100이 돌아오네요 -100이면 이메일과 비밀번호가 맞다는 뜻! 자 이제 그렇다면 Mac인증 안내부분을 보낼차례!


처음 인증하면 한번만 할꺼냐 영원히 할꺼냐를 물어보죠  이부분 리퀘스트를 살펴봅시다



처음 리퀘스트와 똑같고 post에 once=true 가 있네요 . false를 주면 이 맥을 인증한다는 거겠죠. 보내면 Response가 위와 똑같고  헤더는 똑같고 status 가 0 이되네요 0이된다는건 자 기기 알았고 너의 모바일로 인증번호를 보냈어! 라는 뜻이겠네요   전화기를 보면 카톡으로 부터 registration code가 와있겠죠. ( 이 Mac 인증하기를 한번이라도 했으면 이 인증단계는 건너뛰고 다음으로 바로 넘어가네요)



  인증번호를 입력하고 보내는 리퀘스트를 또 살펴봅시다 



뭐 보내는 헤더는 같고 post데이터에 forced와 passcode값이 있네요 forced는 강제 로그인같고(확인은 안해봄ㅎ) passcode에 모바일 카톡으로 온 인증번호를 넣어주시면 됩니다. 자 이렇게 가면 오는 응답은?



이번엔 뭔가가 좀 있네요 status에  0 , 세션키 , 내 정보등등이 옵니다.

다른건 필요없고 sessionKey! 이걸 위해 여기까지 왔습니다.
카카오톡이 이 세션키를 사용하여 접속을 하기 때문에 세션키를 얻었으면 인증과정은 끝!
이 세션키와 위에서 사용한 device_uuid를 -로 묶어서 사용합니다.
세션키를 얻었으니 한번 사용해봅시다.
 
맥용 카톡에선 인증후 "세션키"-"device_uuid"를 이용해 초기 세팅과 친구목록, 블럭한 유저등을 불러오네요
 
친구목록 고고 


이렇게 보내면 응답으로 친구목록이 주루루룩룩.... 
뭐 저의 목적은 얻었으니 post값은 뭔지 찾아보기 귀찮고 ㅎ 
헤더의 "S"필드는 아까 얻은 세션과 device_uuid값을 넣으면 됩니다.
 
개인적으로 device_uuid를 시스템 uuid로 사용하는게 좀 마음에 걸리네요 
누구든지 알아낼수있는 거라 차라리 랜덤생성후 키체인을 사용해 저장해두는것도 나쁘지 않은거 같습니다.
 
이렇게 세션키 얻는과정까지 끝내고 친구목록까지 나오는  프로젝트를 올려두겠습니다. 
Swift 나온참에 Swift로 만들어서 xcode6 가 필요합니다.
OS X 10.10의 플랫한 윈도우 컨트롤버튼이 마음에 들어 이와 비슷하게 커스텀한 윈도우를 만들었는데 
마음에 드네요 ㅎㅎ  


(git : https://github.com/hang-h/KakaoTalk_Mac)

 
 
오늘은 여기까지 쓰겠습니다. 다음엔 원래 얻은 세션키로 Loco서버에 접속해서 메세지 보내는 부분을 쓰려했으나
 
이 과정을 하고 나니 모바일의 처음 가입  및 인증 부분이 궁금해져서 iOS 버전 카톡의 인증 프로세스에 대해 써보도록 하겠습니다.
 
 
ps. 분석하고 글을쓰니 맥용 0.9.1 이 나와있더군요 ㅎㅎ 대충보니 로그인부분은 같고 다른부분이 X-VC 생성할때 쓰는 
 "JOSH" 와 "AUSTIN" 이 "NITSUA" 와 "HSOJ" 로 바뀌어있네요  매 버전마다 이부분을 바꿔쓸듯 합니다.
 
 
 
